server:
  port: 9914

logging:
  file: /opt/hkr-logs/hkr-si.log
  level: DEBUG

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://localhost:3306/hkr_si?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: username
    password: password
    maximum-pool-size: 3
    max-idle: 1
    max-wait: 3
    min-idle: 1
    initial-size: 1
    test-while-idle: true

  #redis
  redis:
    host: localhost
    port: 6379
    pool.max-idle: 8
    pool.min-idle: 1
    pool.max-active: 8
    pool.max-wait: -1

#Cr host
cr:
  host: http://localhost:9924

#notifyUrl
notify:
  url:
    wechat: http://yourhost:port/hkr-si/api/v2/third/callback/we_chat_pay
    alipay: http://yourhost:port/hkr-si/api/v2/third/callback/ali_pay

flyway:
  baselineOnMigrate: true
  table: hkr_si_schema_version
  enabled: true

#环境标示
env:
  tag: 1